server:
  port: 18081
  shutdown: graceful

spring:
  application:
    name: distributed-cloud-module-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.5.100:8848
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-dev.yaml
      - nacos:${spring.application.name}-dev.yaml

springdoc:
  packages-to-scan: com.phoenix.distributed.authorization.controller
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs